name: 'build-docs'
description: ''
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup
    - run: yarn build
      shell: bash
    - run: yarn pvm changelog download
      shell: bash
    - run: yarn build-docs
      shell: bash
