name: 'test repos cleanup'

on:
  schedule:
    - cron: '10 * * * *'

env:
  PVM_LL: silly

jobs:
  github-test-cleanup:
    runs-on: ubuntu-latest
    env:
      PVM_GITHUB_TEST_REPO_TOKEN: ${{ secrets.PVM_GITHUB_TEST_REPO_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - run: node scripts/github-test-repos-cleanup.js
