name: 'pvm update'

on:
  push:
    branches:
      - 'master'

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      PVM_LL: silly
      GITHUB_TOKEN: ${{ secrets.TINKOFF_BOT_PAT }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
          # Because of restriction that actions made with GITHUB_TOKEN are not trigger any actions
          ssh-key: ${{ secrets.DEPLOY_SSH_KEY }}
      - uses: ./.github/actions/setup
      - run: yarn build
      - run: yarn pvm update

  docs:
    runs-on: ubuntu-latest
    container: mshipov/plantuml:0.0.1
    needs: update
    env:
      PVM_LL: silly
      GITHUB_TOKEN: ${{ secrets.TINKOFF_BOT_PAT }}
    permissions:
      contents: write
    concurrency:
      group: docs
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 150
      - uses: ./.github/actions/build-docs
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build
          force_orphan: true
