name: 'pull request'

on: pull_request

jobs:
  mark-pr:
    runs-on: ubuntu-latest
    env:
      PVM_LL: silly
      GITHUB_TOKEN: ${{ secrets.TINKOFF_BOT_PAT }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: ./.github/actions/setup
      - run: npm run build
      - run: npm exec pvm mark-pr

  docs-test:
    runs-on: ubuntu-latest
    container: mshipov/plantuml:1.0.4
    env:
      PVM_LL: silly
      GITHUB_TOKEN: ${{ secrets.TINKOFF_BOT_PAT }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: ./.github/actions/build-docs
      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: ./website/build

  test:
    runs-on: ubuntu-latest
    env:
      PVM_LL: silly
      GITHUB_TOKEN: ${{ secrets.TINKOFF_BOT_PAT }}
      PVM_GITHUB_TEST_REPO_TOKEN: ${{ secrets.PVM_GITHUB_TEST_REPO_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: ./.github/actions/setup
      - uses: dorny/paths-filter@v2
        id: packageChanges
        with:
          filters: |
            changes:
              - 'packages/**'
              - 'test/**'
      - run: npm run build
      - run: npm run check-ts-strict
      - run: npm run lint:config-schema
      - run: npm exec pvm vcs is-branch-actual
      - run: npm exec pvm lint
      - run: npm run lint
      - if: steps.packageChanges.outputs.changes == 'true'
        run: npm run test -- -w `node -p 'Math.min(os.cpus().length, 2)'`
      - run: node scripts/github-test-repos-cleanup.js
        if: always()

  publish-dry-run:
    runs-on: ubuntu-latest
    env:
      PVM_LL: silly
      GITHUB_TOKEN: ${{ secrets.TINKOFF_BOT_PAT }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: ./.github/actions/setup
      - run: npm run build
      - run: npm exec pvm publish -- -s changed-since-release -S ref=HEAD --dry-run

  publish-stale-dry-run:
    runs-on: ubuntu-latest
    env:
      PVM_LL: silly
      GITHUB_TOKEN: ${{ secrets.TINKOFF_BOT_PAT }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: ./.github/actions/setup
      - run: npm run build
      - run: npm exec pvm publish -- -s stale --dry-run

  update-dry-run:
    runs-on: ubuntu-latest
    env:
      PVM_LL: silly
      GITHUB_TOKEN: ${{ secrets.TINKOFF_BOT_PAT }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: ./.github/actions/setup
      - run: npm run build
      - run: npm exec pvm update -- --dry-run
