name: 'release'

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      PVM_LL: silly
      GITHUB_TOKEN: ${{ secrets.TINKOFF_BOT_PAT }}
      PVM_SLACK_TOKEN: ${{ secrets.PVM_SLACK_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      PVM_MATTERMOST_URL: ${{ secrets.PVM_MATTERMOST_URL }}
      PVM_MATTERMOST_TOKEN: ${{ secrets.PVM_MATTERMOST_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: ./.github/actions/setup
      - run: yarn build
      - run: yarn pvm publish
